# Generated by Django 4.2.26 on 2025-11-09 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=80, null=True)),
                ('engine_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads_post.vehiclecategory')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicleimages',
            name='post',
        ),
        migrations.DeleteModel(
            name='UserVehiclePost',
        ),
        migrations.DeleteModel(
            name='VehicleImages',
        ),
    ]
