# Generated by Django 4.2.26 on 2025-11-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_post', '0003_remove_vehicle_image_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_verification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='verification_score',
            field=models.FloatField(blank=True, help_text='AI confidence score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('failed', 'Failed'), ('manual_review', 'Manual Review Required')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_detected_brand', models.CharField(blank=True, max_length=120, null=True)),
                ('ai_detected_model', models.CharField(blank=True, max_length=120, null=True)),
                ('ai_detected_vehicle_type', models.CharField(blank=True, max_length=80, null=True)),
                ('ai_detected_fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_detected_year', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_match_score', models.FloatField(blank=True, null=True)),
                ('model_match_score', models.FloatField(blank=True, null=True)),
                ('vehicle_type_match_score', models.FloatField(blank=True, null=True)),
                ('fuel_type_match_score', models.FloatField(blank=True, null=True)),
                ('image_quality_score', models.FloatField(blank=True, null=True)),
                ('overall_confidence_score', models.FloatField(blank=True, null=True)),
                ('is_vehicle_image', models.BooleanField(default=False)),
                ('images_analyzed_count', models.PositiveIntegerField(default=0)),
                ('ai_raw_response', models.JSONField(blank=True, help_text='Complete AI response for debugging', null=True)),
                ('ai_suggestions', models.TextField(blank=True, help_text='AI suggestions for improvement', null=True)),
                ('discrepancies', models.JSONField(blank=True, help_text='List of discrepancies found', null=True)),
                ('verification_passed', models.BooleanField(default=False)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_results', to='ads_post.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Verification Result',
                'verbose_name_plural': 'Vehicle Verification Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
