# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_post', '0004_vehicle_is_verified_vehicle_last_verification_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the vehicle', null=True),
        ),
    ]

