# Generated by Django 4.2.26
# Data migration to handle duplicate plate numbers before adding unique constraint

from django.db import migrations


def handle_duplicate_plate_numbers(apps, schema_editor):
    """
    Handle duplicate plate numbers by keeping the first occurrence
    and setting subsequent duplicates to NULL with a note in description
    """
    Vehicle = apps.get_model('ads_post', 'Vehicle')
    from collections import defaultdict
    
    # Get all vehicles with plate numbers
    vehicles_with_plates = list(Vehicle.objects.exclude(plate_number__isnull=True).exclude(plate_number=''))
    
    # Group by plate number (case-insensitive, trimmed)
    plate_groups = defaultdict(list)
    for vehicle in vehicles_with_plates:
        plate = vehicle.plate_number.strip() if vehicle.plate_number else None
        if plate:
            plate_groups[plate].append(vehicle)
    
    # Process duplicates
    duplicates_handled = 0
    for plate_number, vehicles in plate_groups.items():
        if len(vehicles) > 1:
            # Sort by created_at to keep the oldest one
            vehicles_sorted = sorted(vehicles, key=lambda v: v.created_at)
            
            # Keep the first one, modify the rest
            for vehicle in vehicles_sorted[1:]:
                # Preserve original plate number in description
                original_plate = vehicle.plate_number
                vehicle.plate_number = None
                
                # Add note to description if it exists
                if vehicle.description:
                    vehicle.description = f"[Original Plate: {original_plate}] {vehicle.description}"
                else:
                    vehicle.description = f"[Original Plate: {original_plate} - Duplicate removed during migration]"
                
                vehicle.save(update_fields=['plate_number', 'description'])
                duplicates_handled += 1
    
    if duplicates_handled > 0:
        print(f"Migration: Handled {duplicates_handled} duplicate plate number(s)")


def reverse_handle_duplicates(apps, schema_editor):
    """
    Reverse migration - cannot restore duplicates automatically
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ads_post', '0005_vehicle_description'),
    ]

    operations = [
        migrations.RunPython(handle_duplicate_plate_numbers, reverse_handle_duplicates),
    ]

