# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_post', '0006_handle_duplicate_plate_numbers'),
    ]

    operations = [
        # Add unique constraint to plate_number
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, help_text='Each vehicle must have a unique plate number', max_length=50, null=True, unique=True),
        ),
        # Add plate number fields to VehicleVerificationResult
        migrations.AddField(
            model_name='vehicleverificationresult',
            name='ai_detected_plate_number',
            field=models.CharField(blank=True, help_text='Plate number detected from images by AI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicleverificationresult',
            name='plate_number_match_score',
            field=models.FloatField(blank=True, help_text='Match score for plate number (0-100)', null=True),
        ),
    ]

