# Generated by Django 5.2.7 on 2025-10-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_email_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nic_image_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
